create table public.memories (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  item_name character varying not null,
  item_location character varying not null,
  item_desc text not null,
  item_obtained_date date not null,
  user_uid uuid null,
  item_image text null,
  constraint Memories_pkey primary key (id)
) TABLESPACE pg_default;